# Управление конфигурацией Supabase
[api]
  enabled = true
 port = 54321
  host = "127.0.0.1"

[db]
  port = 54322
  major_version = 15
  extensions = ["uuid-ossp"]

[studio]
  enabled = true
  port = 54323
  host = "127.0.0.1"

[auth]
  enabled = true
  site_url = "http://localhost:3000"
  additional_redirect_urls = ["https://localhost:3000"]
  jwt_expiry = 3600
  anonymous_sign_ins = false
 # Включение Row Level Security (RLS)
  enable_rls = true

[auth.email]
  enabled = true
  double_opt_in = false

[analytics]
  enabled = false

# Настройки для включения RLS на уровне базы данных
[db.config]
  # Включение Row Level Security по умолчанию для новых таблиц
  enable_row_level_security = true